[package]
name = "xitca-test"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
io-uring = ["xitca-http/io-uring", "xitca-server/io-uring"]

[dependencies]
xitca-client = { workspace = true, features = ["http2", "http3", "websocket", "grpc", "dangerous"] }
xitca-http = { workspace = true, features = ["http2", "http3"] }
xitca-codegen = { workspace = true }
xitca-io =  { workspace = true }
xitca-server = { workspace = true, features = ["quic"] }
xitca-service = { workspace = true }
xitca-unsafe-collection =  { workspace = true }
xitca-web = { workspace = true, features = ["codegen", "compress-zs", "grpc", "http2"] }

http-ws = { workspace = true, features = ["stream"] }

async-stream = { workspace = true }
futures-util = { workspace = true, default-features = true }
h3-quinn = { workspace = true }
prost = { workspace = true, default-features = true }
percent-encoding = { workspace = true }
rustls-pemfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[dev-dependencies]
h2 = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "net", "time"] }

[build-dependencies]
prost-build = { workspace = true }
