[package]
name = "xitca-http-grpc"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2021"

[dependencies]
xitca-http = { version = "0.1", default-features = false, features = ["http2", "util-service"] }
xitca-server= "0.1"
xitca-service = "0.1"

anyhow = "1.0.66"
futures-util = "0.3"
prost = "0.10.3"
tracing = "0.1.26"
tracing-subscriber = { version = "0.3.1", features = ["env-filter"] }

[build-dependencies]
prost-build = "0.10.3"
