[package]
name = "xitca-http-grpc"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2021"

[dependencies]
xitca-http = { version = "0.1", default-features = false, features = ["http2", "util-service"] }
xitca-server= "0.1"
xitca-service = "0.1"

anyhow = "1.0.66"
futures-util = { version = "0.3", default-features = false }
prost = "0.10.3"
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["env-filter", "fmt"] }

[build-dependencies]
prost-build = "0.10.3"
