[package]
name = "xitca-http-worker"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
xitca-web = { version = "0.6.2", default-features = false, features = ["file-raw"] }

console_error_panic_hook = { version = "0.1.1" }
http-file = { version = "0.1", default-features = false }
futures-util = { version = "0.3", default-features = false }
rust-embed = "8"
wasm-bindgen = "0.2.92"
worker = { version = "0.4.0", features = ["http"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
