[package]
name = "xitca-http-worker"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cfg-if = "1.0.0"
http-file = { version = "0.1", default-features = false }
rust-embed = "8"
serde_json = "1.0.89"
worker = "0.0.18"
xitca-http = { version = "0.1", default-features = false, features = ["util-service"] }
xitca-service = "0.1"
xitca-unsafe-collection = "0.1"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile.release]
lto = true
strip = true
codegen-units = 1
