[package]
name = "xitca-http-worker"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
xitca-web = { version = "0.4", default-features = false }
xitca-unsafe-collection = "0.1"

http-file = { version = "0.1", default-features = false }

cfg-if = "1.0.0"
futures-core = "0.3"
rust-embed = "8"
worker = { version = "0.0.24", features = ["http"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile.release]
lto = true
strip = true
codegen-units = 1
