[package]
name = "xitca-web-macros"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2021"

[dependencies]
xitca-web = { version = "0.1", features = ["codegen"] }

thiserror = "1"
