[package]
name = "http-ws"
version = "0.4.1"
edition = "2024"
license = "Apache-2.0"
description = "websocket for http crate type"
repository = "https://github.com/HFQR/xitca-web"
keywords = ["http", "websocket"]
authors = ["fakeshadow <everestshadow@gmail.com>"]
readme= "README.md"
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []
stream = ["pin-project-lite", "tokio/sync"]

[dependencies]
bytes = { workspace = true }
futures-core = { workspace = true, default-features = false }
getrandom = { workspace = true }
http = { workspace = true }
tracing = { workspace = true }

# stream feature
pin-project-lite = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "net", "rt", "time"] }
futures-util = { workspace = true }

[package.metadata.docs.rs]
all-features = true
