[package]
name = "http-encoding"
version = "0.3.0"
edition = "2024"
license = "Apache-2.0"
description = "compression for http crate type"
repository = "https://github.com/HFQR/xitca-web"
keywords = ["http", "compression"]
authors = ["fakeshadow <everestshadow@gmail.com>"]
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []
all = ["br", "gz", "de", "zs"]
br = ["brotli2"]
gz = ["flate2"]
de = ["flate2"]
zs = ["zstd"]

[dependencies]
bytes = { workspace = true }
futures-core = { workspace = true }
http = { workspace = true }
http-body-alt = { workspace = true }
pin-project-lite = { workspace = true }

brotli2 = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
zstd = { workspace = true, optional = true }
