[package]
name = "tokio-uring-xitca"
version = "0.2.2"
authors = ["Tokio Contributors <team@tokio.rs>", "fakeshadow <everestshadow@gmail.com>"]
edition = "2024"
readme = "README.md"
license = "MIT"
repository = "https://github.com/HFQR/xitca-web"
description = """
a fork of tokio-uring with miniaml maintenance
"""
categories = ["asynchronous", "network-programming"]
keywords = ["async", "fs", "io-uring"]
rust-version.workspace = true

[lints]
workspace = true

[features]
bytes = ["dep:bytes"]
runtime = ["dep:tokio"]
runtime-uring = ["runtime", "dep:slab", "dep:libc", "dep:io-uring", "dep:socket2"]

[dependencies]
tokio = { workspace = true, features = ["net", "rt", "sync"], optional = true }
slab = { workspace = true, optional = true }
libc = { workspace = true, optional = true }
io-uring = { workspace = true, optional = true }
socket2 = { workspace = true, features = ["all"], optional = true }
bytes = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio-test = { workspace = true }
iai = { workspace = true }
criterion = { workspace = true }
# we use joinset in our tests
tokio = { workspace = true }
nix = { workspace = true, features = ["resource"] }

[package.metadata.docs.rs]
all-features = true

[[bench]]
name = "lai_no_op"
path = "benches/lai/no_op.rs"
harness = false

[[bench]]
name = "criterion_no_op"
path = "benches/criterion/no_op.rs"
harness = false
