[package]
name = "xitca-web-multipart"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2021"

[dependencies]
xitca-web = { version = "0.1", features = ["multipart"] }

futures-util = { version = "0.3.25", default-features = false }
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["env-filter", "fmt"] }
