[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[example]]
name = "hello-world"
path = "hello-world.rs"

[[example]]
name = "grpc"
path = "grpc.rs"

[[example]]
name = "unix"
path = "unix.rs"

[[example]]
name = "multi-services"
path = "multi-services.rs"

[[example]]
name = "route"
path = "route.rs"

[[example]]
name = "websocket"
path = "websocket.rs"

[[example]]
name = "multipart"
path = "multipart.rs"

[[example]]
name = "io-uring"
path = "io-uring.rs"
required-features = ["io-uring"]

[[example]]
name = "compression"
path = "compression.rs"

[[example]]
name = "tower-http"
path = "tower-http.rs"

[features]
io-uring = ["tokio-uring", "xitca-web/io-uring"]

[dependencies]
xitca-http = { version = "0.1", features = ["http2", "http3", "rustls", "openssl"] }
xitca-io = "0.1"
xitca-server= { version = "0.1", features = ["http3"] }
xitca-service = "0.1"
xitca-web = { version = "0.1", features = ["http2", "http3", "rustls", "openssl", "compress-br", "compress-de", "compress-gz", "multipart", "tower-http-compat", "websocket"] }

http-encoding = { version = "0.1", features = ["all"] }
http-ws = "0.1"

anyhow = "1.0.48"
bytes = "1.2"
futures-util = "0.3"
h3-quinn = "0.0.0"
http = "0.2.8"
mimalloc = { version = "0.1.26", default-features = false }
prost = "0.10.3"
rustls = "0.20"
rustls-pemfile = "1"
tempfile = "3"
tokio = { version = "1.5", features = ["fs", "macros", "rt"] }
tower-http = { version = "0.3", features = ["fs"] }
tracing = "0.1.26"
tracing-subscriber = { version = "0.3.1", features = ["env-filter"] }
openssl = "0.10"

tokio-uring = { version = "0.3", optional = true }

[build-dependencies]
prost-build = "0.10.3"
