[workspace]
resolver = "2"
members = [
    "cloudflare-worker",
    "compression",
    "cookie",
    "dependency-injection",
    "error-handle",
    "file",
    "grpc",
    "hello-world",
    "io-uring",
    "macros",
    "multipart",
    "multi-http-services",
    "streaming",
    "sync",
    "tower-http",
    "unix",
    "wasi",
    "websocket"
]

[profile.dev]
debug-assertions = false
