[workspace]
members = [
    "cloudflare-worker",
    "compression",
    "grpc",
    "hello-world",
    "io-uring",
    "multipart",
    "multi-http-services",
    "tower-http",
    "unix",
    "wasi",
    "websocket"
]

[patch.crates-io]
xitca-http = { path = "../http" }
xitca-io = { path = "../io" }
xitca-server = { path = "../server" }
xitca-service = { path = "../service" }
xitca-web = { path = "../web" }
xitca-unsafe-collection = { path = "../unsafe_collection" }
http-encoding = { path = "../http-encoding" }
http-multipart = { path = "../http-multipart" }
http-ws = { path = "../http-ws" }

h3 = { git = "https://github.com/hyperium/h3.git" }
h3-quinn = { git = "https://github.com/hyperium/h3.git" }
