[package]
name = "xitca-web-compression"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2021"

[dependencies]
xitca-web = { version = "0.2", features = ["compress-br", "compress-de", "compress-gz"] }

tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["env-filter", "fmt"] }
