[package]
name = "xitca-web-io-uring"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2021"

[dependencies]
xitca-http = { version = "0.1", features = ["io-uring", "router", "rustls-uring"] }
xitca-server = { version = "0.1", features = ["io-uring"] }
xitca-service = "0.1"

rcgen = "0.12.0"
rustls = "0.22"
rustls-pki-types = "1"