[package]
name = "xitca-web-io-uring"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2024"

[dependencies]
xitca-http = { version = "0.7", features = ["io-uring", "router", "rustls-uring"] }
xitca-server = { version = "0.5", features = ["io-uring"] }
xitca-service = "0.3"

rcgen = "0.13"
rustls = "0.23"
rustls-pki-types = "1"