name: Setup CI Tools
description: Cache dependencies and install common CI tools (cargo-hack, protoc)

inputs:
  cargo-hack:
    description: Install cargo-hack
    required: false
    default: 'false'
  protoc:
    description: Install protoc
    required: false
    default: 'false'
  cargo-vet:
    description: Install cargo-vet
    required: false
    default: 'false'
  free-disk-space:
    description: Free up disk space (Linux only)
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Cache Dependencies
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

    - name: Free up disk space
      if: inputs.free-disk-space == 'true' && runner.os == 'Linux'
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # main @ 2023-10-18
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Install cargo-hack
      if: inputs.cargo-hack == 'true'
      uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 # v2
      with:
        tool: cargo-hack

    - name: Install protoc
      if: inputs.protoc == 'true'
      uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 # v2
      with:
        tool: protoc@3.23.4

    - name: Install cargo-vet
      if: inputs.cargo-vet == 'true'
      uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 # v2
      with:
        tool: cargo-vet@0.10.2
