[package]
name = "xitca-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
xitca-io = "0.1"
xitca-service = "0.1"
xitca-unsafe-collection = "0.1"

fallible-iterator = "0.2"
futures-core = { version = "0.3", default-features = false }
parking_lot = "0.12.0"
percent-encoding = "2.1.0"
pin-project-lite = "0.2.7"
postgres-protocol = "0.6.2"
postgres-types = "0.2.2"
tokio = { version = "1.14", features = ["sync"] }
tracing = { version = "0.1.32", default-features = false }
