[package]
name = "xitca-postgres"
version = "0.1.0"
edition = "2021"

[features]
# feature for single thread client that have lower overhead(no lock) at the cost of non thread safe.
single-thread = []

[dependencies]
xitca-io = "0.1"
xitca-service = "0.1"
xitca-unsafe-collection = { version = "0.1", features = ["bytes"] }

fallible-iterator = "0.2"
futures-core = { version = "0.3", default-features = false }
percent-encoding = "2.1.0"
postgres-protocol = "0.6.4"
postgres-types = "0.2.3"
tokio = { version = "1.17", features = ["sync"] }
tracing = { version = "0.1.35", default-features = false }

[dev-dependencies]
tokio = { version = "1.17", features = ["rt"] }
