[package]
name = "xitca-postgres"
version = "0.1.0"
edition = "2021"

[features]
# feature for single thread client that have lower overhead(no lock) at the cost of no thread safety.
single-thread = []

[dependencies]
xitca-io = { version = "0.1", features = ["runtime"] }
xitca-service = "0.1"
xitca-unsafe-collection = { version = "0.1", features = ["bytes", "channel"] }

fallible-iterator = "0.2"
futures-core = { version = "0.3", default-features = false }
percent-encoding = "2"
postgres-protocol = "0.6"
postgres-types = "0.2"
tokio = { version = "1.24", features = ["net", "sync"] }
tracing = { version = "0.1", default-features = false }

[dev-dependencies]
tokio = { version = "1.24", features = ["rt"] }
