[package]
name = "xitca-postgres"
version = "0.1.0"
edition = "2021"

[features]
# feature for single thread client that have lower overhead(no lock) at the cost of no thread safety.
single-thread = []
# feature for connecting to tls enabled server.
tls = ["xitca-tls/rustls", "ring", "rustls/dangerous_configuration"]
# feature for using quic as client/server transport layer for better congetion handling on lossy connection.
# note: it does not work as stand alone and server side proxy for translating quic message to tcp is needed.
quic = ["tls", "quinn", "quinn-proto", "rustls-pemfile"]

[dependencies]
xitca-io = { version = "0.1", features = ["runtime"] }
xitca-service = "0.1"
xitca-unsafe-collection = { version = "0.1", features = ["bytes"] }

fallible-iterator = "0.2"
percent-encoding = "2"
postgres-protocol = "0.6.5"
postgres-types = "0.2"
tokio = { version = "1.27", features = ["net", "sync"] }
tracing = { version = "0.1", default-features = false }

# tls
xitca-tls = { version = "0.1", optional = true }
ring = { version = "0.16", optional = true }

# quic
quinn = { version = "0.10", git = "https://github.com/quinn-rs/quinn.git", optional = true }
quinn-proto = { git = "https://github.com/quinn-rs/quinn.git", optional = true }
rustls-pemfile = { version = "1.0.2", optional = true }

# tls and quic shared
rustls = { version = "0.21", optional = true }

[dev-dependencies]
rcgen = "0.10"
tokio = { version = "1.27", features = ["macros", "rt"] }
