[package]
name = "xitca-web-streaming"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2024"

[dependencies]
xitca-web = { version = "0.7", features = ["nightly"] }
futures = "0.3"
async-stream = "0.3"
