name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  clippy-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
    - name: fmt
      run: cargo fmt --all --check