[package]
name = "xitca-web"
version = "0.9.0"
edition = "2024"
license = "Apache-2.0"
description = "an async web framework"
repository = "https://github.com/HFQR/xitca-web"
keywords = ["xitca", "xitca-web"]
authors = ["fakeshadow <everestshadow@gmail.com>"]
readme= "README.md"
rust-version.workspace = true

[lints]
workspace = true

[features]
default = ["http1"]

# extended http versions
http1 = ["__server", "xitca-http/http1"]
http2 = ["__server", "xitca-http/http2"]
http3 = ["__server", "xitca-http/http3", "xitca-server/quic", "xitca-io/quic"]

# linux io-uring runtime and http service
io-uring = ["__server", "xitca-server/io-uring", "xitca-http/io-uring"]

# tls transport layer
openssl = ["__server", "xitca-http/openssl", "xitca-tls/openssl"]
rustls = ["__server", "xitca-http/rustls", "xitca-tls/rustls"]

# params type extractor
params = ["serde"]

# json type extractor/respodner
json = ["serde", "serde_json"]

# urlencoded type extractor
urlencoded = ["serde", "serde_urlencoded" ]

# (de)compression middlewares
compress-br = ["__compress", "http-encoding/br"]
compress-gz = ["__compress", "http-encoding/gz"]
compress-de = ["__compress", "http-encoding/de"]
compress-zs = ["__compress", "http-encoding/zs"]

# cookie handler type
cookie = ["dep:cookie"]

# multipart type extractor
multipart = ["dep:http-multipart"]

# grpc type extractor/responder
grpc = ["http-grpc-rs/stream", "dep:prost", "tokio/time"]

# websocket type extractor/responder
websocket = ["dep:http-ws", "tokio/time"]

# static file serving
file = ["file-raw", "http-file/default"]
# static file serving with io-uring 
file-io-uring = ["io-uring", "file", "http-file/tokio-uring-xitca"]
# static file serving without default file system
file-raw = ["dep:http-file"]

# rate-limit middleware
rate-limit = ["dep:http-rate"]

# tracing logging middleware
logger = ["tracing", "tracing-subscriber"]

# nightly rust required feature.
#
# IMPORTANT note when utilizing nightly feature:
# nightly feature is unstable and would not take part in semver practice. all breaking change 
# origin from it would be seen as non breaking from stable release point of view.
nightly = []

# macro code generation
codegen = ["xitca-codegen"]

# experimental tower-http Layer compat
tower-http-compat = ["tower-service", "tower-layer", "http-body"]

# (de)serialization shared feature.
serde = ["dep:serde_core"]

# private compress shared feature
__compress = ["dep:http-encoding"]

# private http server feature
__server = ["xitca-http/runtime", "xitca-server"]

[dependencies]
xitca-http = { workspace = true, features = ["router"] }
xitca-service = { workspace = true, features = ["alloc"] }
xitca-unsafe-collection = { workspace = true }

futures-core = { workspace = true }
pin-project-lite = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }

# http server
xitca-server = { workspace = true, optional = true }

# tls
xitca-tls = { workspace = true, optional = true }

# (de)serialization shared.
serde_core = { workspace = true, optional = true }

# json
serde_json = { workspace = true, optional = true }

# urlencoded
serde_urlencoded = { workspace = true, optional = true }

# compress-x
http-encoding = { workspace = true, optional = true }

# cookie
cookie = { workspace = true, features = ["percent-encode", "secure"], optional = true }

# grpc
http-grpc-rs = { workspace = true, optional = true }
prost = { workspace = true, optional = true }

# multipart
http-multipart = { workspace = true, optional = true }

# websocket
http-ws = { workspace = true, features = ["stream"], optional = true }

# static file
http-file = { workspace = true, optional = true }

# rate limit
http-rate = { workspace = true, optional = true }

# logger
tracing = { workspace = true, default-features = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

# codegen
xitca-codegen = { workspace = true, optional = true }

# tower-http-compat
tower-service = { workspace = true, optional = true }
tower-layer = { workspace = true, optional = true }
http-body = { workspace = true, optional = true }

# http3
xitca-io = { workspace = true, optional = true }

[dev-dependencies]
xitca-codegen = { workspace = true }
xitca-web = { path = ".", features = ["json"] }

futures-util = { workspace = true, default-features = true, features = ["alloc"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros"] }
tower-http = { workspace = true, features = ["fs", "set-status"] }
tracing = { workspace = true, default-features = true }

[package.metadata.docs.rs]
all-features = true
